# Generated by Django 5.0.6 on 2024-05-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Defalt Title', max_length=300),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
